### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by KlausT** [KlausT/ccminer-cryptonight#4]
Looks like the 64bit build with CUDA 7.5 is broken.
At least under Windows.

**Comment by ZeroASIC** [comment]
CUDA 7.5 gives a memcpy error on Ubuntu 16.04 64bit.  I tracked down a bug for a different project that suggests it might be fixed in CUDA 8.0.

Here's the error I get:
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;

Here's the issue for the other project
https://github.com/BVLC/caffe/issues/4046

**Comment by KlausT** [comment]
I think you get this error because the gcc version is not compatible with your CUDA version.

**Comment by ZeroASIC** [comment]
i just got it to compile by adding -D_FORCE_INLINES to line 394 of the make file:
`NVCC_GENCODE = -D_FORCE_INLINES -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_50,code=\"sm_50\"  -gencode=arch=compute_52,code=\"sm_52,compute_52\"
all: cpuminer-config.h`

**Comment by KlausT** [comment]
Looks like CUDA 7.5 is generally broken.
CUDA 6.5 works without errors, but is not as fast for Pascal cards.
Since Nvidia has released CUDA 8 now, I will test this.

**Comment by KlausT** [comment]
ok, I have tested CUDA 8 now.
Works great, no validation errors.
Using CUDA 8 is recommended now, at least for Maxwell and Pascal cards.

**Comment by ceozero** [comment]
ccminer-cryptonight  is not the  cudart32_80.dll... where is the cudart32_80.dll? thank you.

**Comment by KlausT** [comment]
the dll is build into the exe
It should work without it
